---
name: fish-lsp
description: LSP implementation for the fish shell langauge
homepage: https://www.fish-lsp.dev/
licenses:
  - MIT
languages:
  - Fish
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/ndonfris/fish-lsp@b46dab6f0964337e2dddb8056d124d8f0a653b01
  build:
    run: |
      yarn install

bin:
  fish-lsp: bin/fish-lsp
