---
name: fish-lsp
description: LSP implementation for the fish shell langauge
homepage: https://www.fish-lsp.dev/
licenses:
  - MIT
languages:
  - Fish
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/ndonfris/fish-lsp@730eab3b0c57cac4eacdf5ab5c4b9635c3242ede
  build:
    run: |
      yarn install

bin:
  fish-lsp: bin/fish-lsp
