---
name: fish-lsp
description: LSP implementation for the fish shell langauge
homepage: https://www.fish-lsp.dev/
licenses:
  - MIT
languages:
  - Fish
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/ndonfris/fish-lsp@a25dd1d9aa462574fc92aabb4e4eb656e64fdc89
  build:
    run: |
      yarn install

bin:
  fish-lsp: bin/fish-lsp
