---
name: fish-lsp
description: LSP implementation for the fish shell langauge
homepage: https://www.fish-lsp.dev/
licenses:
  - MIT
languages:
  - Fish
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/ndonfris/fish-lsp@805784be6784f85e28005cca35baf621b99f5fef
  build:
    run: |
      yarn install

bin:
  fish-lsp: bin/fish-lsp
