---
name: fish-lsp
description: LSP implementation for the fish shell langauge
homepage: https://www.fish-lsp.dev/
licenses:
  - MIT
languages:
  - Fish
categories:
  - LSP

source:
  # renovate:datasource=github-tags
  id: pkg:github/ndonfris/fish-lsp@c73c985ebc66
  build:
    run: |
      yarn install

bin:
  fish-lsp: bin/fish-lsp
