---
name: lx
description: A luxurious package manager for Lua
homepage: https://github.com/lumen-oss/lux
licenses:
  - LGPL-3.0+
languages:
  - Lua
categories:
  - LSP

source:
  id: pkg:github/lumen-oss/lux@v0.25.2
  asset:
    - target: linux_x64_gnu
      file: lx_{{ version | strip_prefix "v" }}_x86_64.tar.gz
      bin: exec:usr/bin/lx
      pkgconfig: usr/lib/pkgconfig/
      fish: usr/share/fish/
      lux: usr/share/lux-lua/
      man: usr/share/man/

bin:
  lx: "{{source.asset.bin}}"

# TODO: don't seem work properly, use `nix profile add` instead
share:
  pkgconfig/: "{{source.asset.pkgconfig}}"
  fish/: "{{source.asset.fish}}"
  lux-lua/: "{{source.asset.lux}}"
  man/: "{{source.asset.man}}"
