---
name: lx
description: A luxurious package manager for Lua
homepage: https://github.com/lumen-oss/lux
licenses:
  - LGPL-3.0+
languages:
  - Lua
categories:
  - LSP

source:
  id: pkg:github/lumen-oss/lux@v0.20.1
  asset:
    - target: linux_x64_gnu
      file: lx_{{ version | strip_prefix "v" }}_x86_64.AppImage
      bin: exec:lx_{{ version | strip_prefix "v" }}_x86_64.AppImage

bin:
  lx: lx.AppImage
