---
name: autocorrect
description:
 A linter and formatter to help you to improve copywriting, correct spaces,
 words, and punctuations between CJK (Chinese, Japanese, Korean).
homepage: https://huacnlee.github.io/autocorrect
licenses:
  - MIT
languages:
  - Markdown
categories:
  - LSP
  - Linter
  - Formatter

source:
  # renovate:datasource=github-tags
  id: pkg:github/huacnlee/autocorrect@v2.15.0
  build:
    - target: unix
      run: |
        cargo build --release --package autocorrect-cli
      bin: target/release/autocorrect

bin:
  autocorrect: "{{source.build.bin}}"
