---
name: emmylua_ls
description: Lua language server in rust.
homepage: https://github.com/CppCXY/emmylua-analyzer-rust
licenses:
  - MIT
languages:
  - Lua
categories:
  - LSP

source:
  id: pkg:cargo/emmylua_ls@0.7.1

bin:
  emmylua_ls: cargo:emmylua_ls
